---
    - name: Add Firewall Rules
      firewalld:
        port: 80/tcp
        permanent: true
        state: enabled
    - name: Reload Firewall Configuration
      systemd:
        name: firewalld
        state: reloaded
    - name: Copy Index File to Apache Directory
      copy:
        src: files/index.html
        dest: /var/www/html
...
