---
- name: Change user password for user
  hosts: 10.0.2.4
  vars:
#   mypassword: "oracle"
   mypassword: "{{ PWDS }}" 

  tasks:

  - name: change password
    user:
      name: "{{ item }}"
      state: present
      password: "{{ mypassword | password_hash('sha512')  }}"
    with_items:
      - demouser1
      - steph
...
# export PWDS="Some Password"
# ansible-playbook change_password.yml -e mypassword='{{ lookup("env", "PWDS") }}'
