---
- name: Configuration Apache Web Server
  hosts: 10.0.2.4
  tasks:
    - name: Install Apache Packages
      yum:
        name: httpd
        state: present
    - name: Start Apache Service
      service:
        name: httpd
        state: started
    - name: Add Firewall Rules
      firewalld:
        port: 80/tcp
        permanent: true
        state: enabled
    - name: Reload Firewall Configuration
      systemd:
        name: firewalld
        state: reloaded
    - name: Copy Index File to Apache Directory
      copy:
        src: /home/fogun/ansible_tutorial/index.html
        dest: /var/www/html
    - name: Restart  Apache Service
      service:
        name: httpd
        state: restarted
...

