--- 
- hosts: all 
  gather_facts: yes
  become: true 
  tasks: 
  
    - name: starting httpd
      service: 
        name=httpd 
        state=started 
        enabled=yes
          
    - name: httpd status 
      command: service httpd status 
      register: httpd_status
         
    - name: httpd status output 
      debug: 
        var: httpd_status.stdout_lines
